### ISSUE TITLE
RuntimeError: numel: integer multiplication overflow

### ISSUE THREAD

**Issue by praeclarumjj3** [IDEA-Research/OpenSeeD#18]
Hi, thanks for sharing your work. 

I followed the recommended environment setup instructions and ran into the following error while trying to run the demo. I am using python 3.9 (if that plays a role here). Looking forward to any suggestions to fix the error. Thanks.

```
RuntimeError: numel: integer multiplication overflow
```

The complete traceback for your reference:

```
Traceback (most recent call last):
  File "/home/jj/OpenSeeD/demo/demo_panoseg.py", line 107, in <module>
    main()
  File "/home/jj/OpenSeeD/demo/demo_panoseg.py", line 86, in main
    outputs = model.forward(batch_inputs)
  File "/home/jj/OpenSeeD/openseed/BaseModel.py", line 19, in forward
    outputs = self.model(*inputs, **kwargs)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jj/OpenSeeD/openseed/architectures/openseed_model.py", line 299, in forward
    processed_results = self.forward_seg(batched_inputs, task=inference_task)
  File "/home/jj/OpenSeeD/openseed/architectures/openseed_model.py", line 434, in forward_seg
    instance_r = retry_if_cuda_oom(self.instance_inference)(mask_cls_result, mask_pred_result, mask_box_result)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/home/jj/OpenSeeD/openseed/architectures/openseed_model.py", line 558, in instance_inference
    print(scores, keep)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/_tensor.py", line 427, in __repr__
    return torch._tensor_str._str(self, tensor_contents=tensor_contents)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/_tensor_str.py", line 637, in _str
    return _str_intern(self, tensor_contents=tensor_contents)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/_tensor_str.py", line 568, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/_tensor_str.py", line 328, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/home/jj/anaconda3/envs/openseed/lib/python3.9/site-packages/torch/_tensor_str.py", line 115, in __init__
    nonzero_finite_vals = torch.masked_select(
RuntimeError: numel: integer multiplication overflow
```

**Comment by YuyanHuang** [comment]
Hi,
Have you solved this problem? I also ran into a similar problem:
`anaconda3/envs/seg/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
self.task_switch  {'coco': True, 'o365': False}
anaconda3/envs/seg/lib/python3.9/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [96,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [97,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [98,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/mnt/d/ubuntu2004/OpenSeeD/demo/demo_panoseg.py", line 107, in <module>
    main()
  File "/mnt/d/ubuntu2004/OpenSeeD/demo/demo_panoseg.py", line 86, in main
    outputs = model.forward(batch_inputs)
  File "/mnt/d/ubuntu2004/OpenSeeD/openseed/BaseModel.py", line 19, in forward
    outputs = self.model(*inputs, **kwargs)
  File "anaconda3/envs/seg/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/d/ubuntu2004/OpenSeeD/openseed/architectures/openseed_model.py", line 299, in forward
    processed_results = self.forward_seg(batched_inputs, task=inference_task)
  File "/mnt/d/ubuntu2004/OpenSeeD/openseed/architectures/openseed_model.py", line 434, in forward_seg
    instance_r = retry_if_cuda_oom(self.instance_inference)(mask_cls_result, mask_pred_result, mask_box_result)
  File "/home/hyy/anaconda3/envs/seg/lib/python3.9/site-packages/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/mnt/d/ubuntu2004/OpenSeeD/openseed/architectures/openseed_model.py", line 558, in instance_inference
    scores_per_image = scores_per_image[keep]
RuntimeError: numel: integer multiplication overflow`

‘ python demo/demo_panoseg.py evaluate --conf_files configs/openseed/openseed_swint_lang.yaml  --image_path images/street.jpg --overrides WEIGHT ckpt/model_state_dict_swint_51.2ap.pt’

torch=1.13.1+cu116
torchvision=0.14.1+cu116
detectron2=0.6
ubuntu=20.04

Thanks.

**Comment by yvfengZhong** [comment]
It's about the "background", see https://github.com/IDEA-Research/OpenSeeD/issues/11.

**Comment by HaoZhang534** [comment]
@praeclarumjj3 @YuyanHuang Sorry for the late reply, we have fixed the bug.
